version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000' # Vue dev server
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  docs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: asciidoctor -r asciidoctor-diagram -a plantuml-format=svg -o docs/dist/architecture.html docs/architecture.adoc
  build:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: npm run build
