# Use Node.js LTS as base image
FROM node:24-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the project
COPY . .

EXPOSE 3000

# Default command
CMD ["npm", "run", "dev"] 